Task 4 first commit.
feperessim/codeminer42-trainee-semana-2 pull request #5
Opened 2022-01-25 18:36 UTC by feperessim

2022-02-02 14:37 UTC, brunohkbx commented on parser.rb
>      { @filename_with_path => {
da pra identar melhor essa hash aqui

2022-02-02 14:37 UTC, brunohkbx commented on parser.rb
> +    end.compact.uniq - ['<world>']
Talvez mover esse `['<world>']` para uma constante na classe? algo como IGNORED_PLAYERS

2022-02-02 14:37 UTC, brunohkbx commented on spec/parser_spec.rb
> +                   "Isgalamido"=> 187,  "Dono da Bola"=> 103, "Mocinha"=> 0, "Zeh"=> 158, "Assasinu Credi"=> 143, "Fasano Again"=> 0,
@feperessim não seria melhor trabalhar com uma fixture mais compacta? É impossível pra qualquer 1 averiguar esses resultados devido aos números altos.

2022-02-02 14:37 UTC, brunohkbx commented on parser.rb
> +    re_pattern_players = /(?:Kill:.*:) (.*) (?:killed) (.*) (?:by)|(?:ClientUserinfoChanged:.*n\\)(.*)(?:\\t\\0\\model.*)/
O que acha de mover isso para uma constante no topo da classe tb?

2022-02-02 15:24 UTC, feperessim commented on parser.rb
>      { @filename_with_path => {
Eu adicionei duas linhas extras de identação, porém o rubocop fica pedindo para removê-las. Devo ignorar o aviso do rubocop ou eu estou tentando identar de maneira incorreta?

2022-02-02 15:25 UTC, feperessim commented on spec/parser_spec.rb
> +                   "Isgalamido"=> 187,  "Dono da Bola"=> 103, "Mocinha"=> 0, "Zeh"=> 158, "Assasinu Credi"=> 143, "Fasano Again"=> 0,
Sim. Eu vou adicionar um arquivo de testes mais compacto e vou mudar os testes de acordo. Muito obrigado pela sugestão.

2022-02-08 13:52 UTC, halan requested changes

2022-02-08 13:52 UTC, halan commented on main.rb
> +    puts 'The class could not be instantiated because the file does not exist.'
Essa mensagem pode mentir sobre o erro. Você não sabe se o arquivo não existe pois tá capturando um `StandardError`, que pode ser qualquer erro.

2022-02-08 13:52 UTC, halan commented on parser.rb
> +    File.open(@filename_with_path, &:readline)
A cada `open` um erro de leitura pode acontecer. Considere isso. Mas nem sempre você precisa tratar um erro, as vezes é melhor o erro de leitura estourar que tratar de forma não tão eficiente.

2022-02-08 13:52 UTC, halan commented on parser.rb
> +    File.open(@filename_with_path, &:readline)
Pode também usar readlines como fez nos demais métodos:

```rb
File.readlines(@filename_with_path).first
```

Mas ainda mantém o aviso que fiz no comentário anterior, já que um File.readlines contém um open internamente.

2022-02-08 13:52 UTC, halan commented on parser.rb
> +    File.readlines(@filename_with_path).flat_map do |line|
Considere memoizar o `File.readlines(@filename_with_path)`

```rb
def file_readlines
  @file_readlines ||= File.readlines(@filename_with_path)
end
```

2022-02-08 13:52 UTC, halan commented on spec/parser_spec.rb
> +                                                                         'players' => players, 'kills' => kills, 'total_kills' => total_kills })
Os lets são excelentes para construir um contexto e memoizá-los, mas não há ganhos em colocá-los do lado direito de uma expectation. a variável `parser` e a `json_parsed_file` são ótimas candidatas a virarem `lets`, pois elas descrevem um contexto e cai bem memoizá-las.

Em outras palavras, os lets preparam o contexto do seu teste, eles não servem pra ser a expectativa do seu teste (até podem ser usados com esse propósito, mas não como o único propósito, um exemplo de uso correto é o `filename_with_path.to_s`)

Mais informações em:

https://www.betterspecs.org/#let


```suggestion
        expect(json_parsed_file).to include(filename_with_path.to_s => {
          'lines' => 33,
          'players' => ['Isgalamido', 'Dono da Bola', 'Oootsimo', 'Assasinu Credi', 'Zeh', 'Mal'],
          'kills' => {'Isgalamido' => 1, 'Dono da Bola' => 5, 'Oootsimo' => 3, 'Assasinu Credi' => 1, 'Zeh' => 2, 'Mal' => 0},
          'total_kills' => 16 })
```

2022-02-15 18:48 UTC, halan approved these changes

2022-02-15 23:16 UTC, merged